DevOrg/force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOrg/force-app/main/default/objects/Company__c/fields/Maximum_Salary__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Salary__c</fullName>
    <label>Maximum Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DevOrg/force-app/main/default/objects/Company__c/fields/Minimum_Salary__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Salary__c</fullName>
    <label>Minimum Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DevOrg/force-app/main/default/objects/Employee__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOrg/force-app/main/default/classes/MinMaxSalarytriggerhelper.cls
public class MinMaxSalarytriggerhelper {
    public static void trgMethod(List<Employee__c> emplist, Map<id,Employee__c>oldEmpMap){
        List<Employee__c> employeeList = new list<Employee__c>();
        List<Id> companyId = new List<id>();
        if(!emplist.isEmpty()){
            for(Employee__c emp : emplist){
                if(oldEmpMap!=null){
                    if(emp.company__c != oldEmpMap.get(emp.id).company__c){
                       
                        companyId.add(oldEmpMap.get(emp.id).company__c);
                        companyId.add(emp.company__c);
                    }
                    else{
                        companyId.add(emp.Company__c);
                    }
                }
                else{
                    companyId.add(emp.Company__c);
                }
                
            }
        }
        Map<id,Company__c> newMapCompany = new Map<id,Company__c>();
        List<AggregateResult> agResult = [Select Company__c cmId, MIN(Salary__c) minSalary, MAX(Salary__c) maxSalary FROM Employee__c where Company__c IN :  companyId GROUP BY Company__c ];
        for(AggregateResult ag :agResult){
            Company__c cmp = new Company__c();
            cmp.Id=(Id)ag.get('cmId');
            cmp.Maximum_Salary__c=(Decimal)ag.get('maxSalary');
            cmp.Minimum_Salary__c=(Decimal)ag.get('minSalary');
            newMapCompany.put(cmp.id,cmp);
        }
        if(!newMapCompany.isEmpty()){
            update newMapCompany.values();
        }
    }
    
}